apiVersion: v1
kind: Service
metadata:
  name: planning-manage-ui
  namespace: planning-manage
spec:
  type: NodePort
  selector:
    app: planning-manage-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
